apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: postgres
type: Opaque
stringData:
  POSTGRES_USER: "oci_admin"
  POSTGRES_PASSWORD: "<CHANGE_ME_IN_PRODUCTION_POSTGRES_PASS>"
