apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: apps
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "oci_rabbit"
  RABBITMQ_DEFAULT_PASS: "<CHANGE_ME_IN_PRODUCTION_RABBITMQ_PASS>"
  MEILI_MASTER_KEY: "<CHANGE_ME_IN_PRODUCTION_MEILI_KEY_32BYTES>"
  ZITADEL_MASTERKEY: "<CHANGE_ME_IN_PRODUCTION_ZITADEL_MASTERKEY_32BYTES>"
  NEXTCLOUD_ADMIN_USER: "admin"
  NEXTCLOUD_ADMIN_PASSWORD: "<CHANGE_ME_IN_PRODUCTION_NEXTCLOUD_PASS>"
  POSTGRES_PASSWORD: "<CHANGE_ME_IN_PRODUCTION_POSTGRES_PASS>"
  FORGEJO_DB_PASSWD: "<CHANGE_ME_IN_PRODUCTION_FORGEJO_PASS>"
