apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: apps
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "oci_rabbit"
  RABBITMQ_DEFAULT_PASS: "oci_rabbit_pass"
  MEILI_MASTER_KEY: "oci_meilisearch_master_key_32bytes"
  ZITADEL_MASTERKEY: "MasterKeyForZitadel32BytesLong!!"
  NEXTCLOUD_ADMIN_USER: "admin"
  NEXTCLOUD_ADMIN_PASSWORD: "oci_nextcloud_admin_pass"
  POSTGRES_PASSWORD: "oci_secure_pass"
  FORGEJO_DB_PASSWD: "oci_secure_pass"
  HBOX_AUTH_API_KEY_PEPPER: "oci_homebox_secret_pepper_min_32_bytes_long!!"
