apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebox
  namespace: apps
  labels:
    app: homebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homebox
  template:
    metadata:
      labels:
        app: homebox
    spec:
      containers:
        - name: homebox
          image: sysadminsmedia/homebox:latest
          ports:
            - containerPort: 7745
              name: http
          env:
            - name: HBOX_MODE
              value: production
            - name: HBOX_WEB_PORT
              value: "7745"
            - name: HBOX_AUTH_API_KEY_PEPPER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: HBOX_AUTH_API_KEY_PEPPER
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: homebox-service
  namespace: apps
  labels:
    app: homebox
spec:
  ports:
    - port: 7745
      targetPort: 7745
      name: http
  selector:
    app: homebox
