apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: apps
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:28-apache
          ports:
            - containerPort: 80
              name: http
          env:
            - name: POSTGRES_HOST
              value: postgres-service.postgres.svc.cluster.local
            - name: POSTGRES_DB
              value: oci
            - name: POSTGRES_USER
              value: oci_admin
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: NEXTCLOUD_ADMIN_USER
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: NEXTCLOUD_ADMIN_PASSWORD
            - name: REDIS_HOST
              value: valkey-service.apps.svc.cluster.local
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
  namespace: apps
  labels:
    app: nextcloud
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: nextcloud
