apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: apps
  labels:
    app: valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:7.2-alpine
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: valkey-service
  namespace: apps
  labels:
    app: valkey
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: valkey
