apiVersion: apps/v1
kind: Deployment
metadata:
  name: zitadel
  namespace: apps
  labels:
    app: zitadel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zitadel
  template:
    metadata:
      labels:
        app: zitadel
    spec:
      containers:
        - name: zitadel
          image: ghcr.io/zitadel/zitadel:v2.48.0
          args:
            - start-from-init
            - --masterkey
            - "$(ZITADEL_MASTERKEY)"
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: ZITADEL_MASTERKEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ZITADEL_MASTERKEY
            - name: ZITADEL_DATABASE_POSTGRES_HOST
              value: postgres-service.postgres.svc.cluster.local
            - name: ZITADEL_DATABASE_POSTGRES_PORT
              value: "5432"
            - name: ZITADEL_DATABASE_POSTGRES_DATABASE
              value: oci
            - name: ZITADEL_DATABASE_POSTGRES_USER_USERNAME
              value: oci_admin
            - name: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE
              value: disable
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zitadel-service
  namespace: apps
  labels:
    app: zitadel
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: zitadel
